# ========================
# HTTP -> HTTPS
# ========================

#server {

#    listen 80;

#    server_name erp.local;

#    return 301 https://$host$request_uri;

#}

# ========================
# DESARROLLO
# ========================

server {

    #listen 443 ssl;
    listen 80;
    #server_name erp.local;
    
    #ssl_certificate     /ssl/erp.local.pem;

    #ssl_certificate_key /ssl/erp.local-key.pem;

    root /var/www/apsy_fe;

    index index.html;

    location / {

        try_files $uri $uri/ /index.html;

    }

    location /api/ {

        proxy_pass http://apsy_core:9000/;

    }

    location /ws/ {

        proxy_pass http://apsy_core:9000/ws/;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;

    }

    location /dev/ {

        proxy_pass http://apsy_core:9009/;

    }

    access_log /logs/dev-access.log;

    error_log /logs/dev-error.log;

}